### ISSUE TITLE
Dev environment performance

### ISSUE THREAD

**Issue by tlfbrito** [janit/docker.sf#1]
This is more a question, not an issue.

Are u using this with mac os X ? If yes, how long does it take your request in dev environment ?

**Comment by sbacelic** [comment]
I tried it on OSX with Docker for Mac - it's just too slow for development. Check out this thread: https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076

**Comment by tlfbrito** [comment]
@sbacelic Thanks for your reply.
